version: '3.3'

services:
  web: &web_base
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    entrypoint: './docker/entrypoints/web.sh'
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
      - '35729:35729'
    volumes:
      - 'bundle_cache:/bundle'
      - 'dockerapp-sync:/dockerapp:nocopy'
      - '.:/dockerapp'
    env_file:
      - '.env'
    stdin_open: true
    tty: true

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'supersecret'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass supersecret
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *web_base
    entrypoint: './docker/entrypoints/sidekiq.sh'
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - 'web'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
  bundle_cache:
  dockerapp-sync:
    external: true
