version: '3.3'

services:
  app: &app_base
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    entrypoint: './docker-entrypoint.sh'
    command: bundle exec puma
    ports:
      - '3000:3000'
    volumes:
      - 'bundle_cache:/bundle'
      - 'app-sync:/app:nocopy'
    env_file:
      - '.env'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'supersecret'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass supersecret
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - 'app'

volumes:
  app-sync:
    external: true
  redis:
  postgres:
  bundle_cache:
